# Generated by Django 2.2.6 on 2019-10-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ManyToManyField(to='app01.User'),
        ),
        migrations.AddField(
            model_name='studentshop',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentshop',
            name='order_number',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
