# Generated by Django 2.2.6 on 2019-11-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.CharField(default='无', max_length=100),
        ),
    ]
