# Generated by Django 2.2.6 on 2019-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191002_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.ManyToManyField(blank=True, to='app01.User'),
        ),
        migrations.AlterField(
            model_name='studentshop',
            name='money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='studentshop',
            name='order_number',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
