# Generated by Django 2.2.6 on 2019-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '__first__'),
        ('login', '0002_auto_20191029_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ManyToManyField(blank=True, to='app01.School'),
        ),
    ]
