# Generated by Django 2.2.6 on 2019-10-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191029_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': '员工用户', 'verbose_name_plural': '员工用户'},
        ),
    ]
